version: '3.1'

services:
    postgres_service:
        image: postgres:15.1
        container_name: postgres_container
        restart: always
        environment:
            POSTGRES_DB: jose_db
            POSTGRES_USER: root
            POSTGRES_PASSWORD: psw1234
        ports:
            - 5432:5432